-- USER SQL
ALTER USER PDB1ADMIN
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER PDB1ADMIN 
QUOTA 100M ON USERS;

-- ROLES
ALTER USER PDB1ADMIN DEFAULT ROLE CONNECT;

-- SYSTEM PRIVILEGES
GRANT CREATE TABLE TO PDB1ADMIN ;
GRANT CREATE VIEW TO PDB1ADMIN ;
GRANT CREATE SEQUENCE TO PDB1ADMIN ;
GRANT CREATE TRIGGER TO PDB1ADMIN ;
GRANT CREATE PROCEDURE TO PDB1ADMIN ;
GRANT CREATE MATERIALIZED VIEW TO PDB1ADMIN ;
GRANT CREATE SYNONYM TO PDB1ADMIN ;
GRANT CREATE PUBLIC SYNONYM TO PDB1ADMIN ;
GRANT CREATE USER TO PDB1ADMIN ;
GRANT CREATE ROLE TO PDB1ADMIN ;
GRANT DROP USER TO PDB1ADMIN ;

